name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  organization:
    description: 'Your input description here'
    required: true
  project:
    description: 'Your input description here'
    required: true
  domain:
    description: 'Your input description here'
    required: true

# Define your outputs here.
outputs:
  pushId:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
