name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  organization:
    description: 'Your organization slug'
    required: true
  project:
    description: 'Your project slug'
    required: true
  domain:
    description: 'Your domain'
    required: false
  files:
    description: 'Space separated list of files/folders to fetch'
    required: true
  mountPath:
    description: 'Your remote content mount path'
    required: true
  maxExecutionTime:
    description: 'Max execution time in milliseconds'
    required: false
  redoclyConfigPath:
    description: 'Path to the redocly config file'
    required: false
  githubToken:
    description: 'Token to authenticate with'
    required: true
    default: ${{ github.token }}
  disableCommitStatusPrefix:
    description:
      'Disable commit status prefix. By default we use orgSlug/projectSlug
      prefix'
    required: false
  customCommitStatusPrefix:
    description: 'Custom commit status prefix. Default is orgSlug/projectSlug'
    required: false

# Define your outputs here.
outputs:
  pushId:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
