name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}
  REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install modules
        id: install-modules
        run: npm install

      - name: Start fake server
        id: fake-server-start
        run: npm run fake-server:start

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          organization: 'test'
          project: 'test'
          domain: 'localhost:3050'
          files: 'test1 test2'
          mountPath: 'test-folder'

      - name: Stop fake server
        id: fake-server-stop
        run: npm run fake-server:stop

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.pushId }}"
